# Matrix Math Refresher

## Data Dimensions

-  Shapes of data

    - single number like a height
    
        - scalars (have 0 dimensions)
    
    - list of numbers of features, like height, weight, age
    
        - vectors, row vectors and column vectors
        
        - hold same data but conceptually they are like below:     
            ```
            row vector = [1,2,3]
            1*3 matrix
            
            col vector  =
            [1]
            [2]
            [3]
            3*1 matrix
            ```
            
         - Personal preference or it affects the math we can do
         
         - 1 dimension in length or called slice
         
         - length of 3
                
    - image of person with rows and columns of pixels
    
        - each pixel might be 3 numbers (R, G, B)
        
        - matrix: 2d grid of values
        
        - we describe it in terms of rows and columns
        
        ```
        [1,2,3]
        [4,5,6]
        2 * 3 matrix, 2 rows 3 column
        ```
        - index it like $a_{12}$
        
     - Tensors
     
         - any n dimensional data value
         
             - scalar: 0-d tensor
             
             - vector: 1-d tensor
             
             - matrix: 2-d tensor
             
             - tensor: n-d tensor
             
        - we could store image with seperate red green blue as a 3-d tensor
             
    - higher dimensions are harder to visualize
    
     
        
- We can talk about these shapes in terms of data dimensions

In [3]:
import numpy as np

In [5]:
# Scalar
s = np.array(5)
s

array(5)

In [6]:
# Even though a scalar is in an array, we can use it like a 
# normal number
x = s + 3
x

8

In [9]:
# we can see that it has 0 dimensions
s.shape

()

In [10]:
# Vector
v = np.array([1,2,3])

In [11]:
# We can see it has 1 dimension and we get its row length
v.shape

(3,)

In [20]:
# Matrix
m = np.array([[1], [2], [3]])
m

array([[1],
       [2],
       [3]])

In [16]:
# 3 * 1 matrix
m.shape

(3, 1)

In [21]:
m = np.array([[1,2], [3,4], [5,6]])
m

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
m.shape

(3, 2)

In [22]:
# Tensor
t = np.array([[[[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

In [23]:
t

array([[[[ 1],
         [ 2]],

        [[ 3],
         [ 4]],

        [[ 5],
         [ 6]]],


       [[[ 7],
         [ 8]],

        [[ 9],
         [10]],

        [[11],
         [12]]],


       [[[13],
         [14]],

        [[15],
         [16]],

        [[17],
         [17]]]])

In [24]:
t.shape

(3, 3, 2, 1)

In [25]:
# Changing shape
v = np.array([1,2,3,4])
v.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

## Element - wise Matrix

- we can treat each item in matrix indlivual with n dimensions

- scalar plus matrix will add that scalar value to each element in the matrix

    - works with all operations +, -,  *, /

- we can add, multiply, divide,  with same shaped matrix

In [32]:
x = x.reshape(2,2)

In [37]:
x * 5

array([[ 5, 10],
       [15, 20]])

In [38]:
x + 5

array([[6, 7],
       [8, 9]])

In [39]:
x + x

array([[2, 4],
       [6, 8]])

## Matrix Multipication (Matrix Product)

- Doesn't usually mean $X * X$

- usually means the dot product

```
[0,2,4,6]
.
[1,7,13,19]

= 0*1 + 2 *7  + 4 *  13 + 6 * 19 

```

- we multiply the rows of the first matrix by the columns of the second  matrix

```
originally a 2 * 4 and a 4 * 3 matrix
[0,2,4,6] . [1]
            [7]
            [13]
            [19]
            
= 0 * 1 + 2 * 7 + 4 * 13 + 6 * 19 = 180

[180, _, _]
[_, _, _]

```


Notice the columns of left have to match number of rows of right

NOtice that our new matrix gets its rows from the left matrix and thr columns from the right

In [40]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [44]:
b =  np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [45]:
a.shape, b.shape

((2, 4), (4, 3))

In [47]:
c = np.dot(a, b)

In [48]:
c.shape

(2, 3)

## Matrix Transpose:

- Swith the columns and rows of the matrix

In [54]:
a, a.shape

(array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 (2, 4))

In [55]:
np.transpose(a), np.transpose(a).shape

(array([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]]),
 (4, 2))

## Wikipedia page notes:

### What is linear algebra used for

- used in all areas of math

    - geometry for defining basic objects, functional analysis, science and engineerign for modelling phenomena
    
    - approximations in non linear systems by taking the derivative at a point of a multivariate function
    
### History

- Gaussian elimination came first in ancient china

    - it is also known as row reduction. It solves a system of linear equations
    
    - It can be understood as a sequence of operations performed on the corresponding matrix of coefficient
    
    - we can use this to find a
    
        - rank
        
        - determinant
        
        - inverse of an invertible square matrix
        
    - We can use a sequence of elementary row operations to modify tghe matrix until the lower left hand corer of the martix is filled with 0s
    
- row operations

    - swapping two rows
    
    - multiplying a row by a nonzero number
    
    - adding a multiple of one row to another
    
- Using gaussian elimination, a matrix can be transformed into an upper trianglular matrix, and one that is in row echelon form

![](alg_gaussian_elimination.png)

We end up getting to reduced row echelon form in last step of algorithm, and we solved the system of equations



### What is linear algebra:

- Linear Algebra purpose: Linear algebra is the branch of mathematics concerning linear equations such as $(x_1,...,x_n) \rightarrow a_1x_1 + ... + a_nx_n$ iand their representation in vector spaces through matrices

- vector space: A vector space (also called a linear space) is a collection of objects called vectors, which may be added together and multiplied ("scaled") by numbers, called scalars. 

    -  A vector space is a set V on which two operations + and · are defined, called vector addition and scalar multiplication
    
    - [vector operation definitions in a vector space](http://www.math.niu.edu/~beachy/courses/240/06spring/vectorspace.html)
    
  
- Vector space made up of linear subspaces: In mathematics, and more specifically in linear algebra, a linear subspace, also known as a vector subspace[1][2] is a vector space that is a subset of some larger vector space

    - We define a vector space on a field: In mathematics, a field is a set on which addition, subtraction, multiplication, and division are defined and behave as the corresponding operations on rational and real numbers do. A field is thus a fundamental algebraic structure which is widely used in algebra, number theory, and many other areas of mathematics.
  

- vectors: a quantity having direction as well as magnitude, especially as determining the position of one point in space relative to another.

- linear combinations: A linear combination of two or more vectors is the vector obtained by adding two or more vectors (with different directions) which are multiplied by scalar values $ v = a_1 \overrightarrow{v_1} + ... + a_n \overrightarrow{v_n}$

    -  linear combinations usually used in the context of a vector space over a field, with some generalizations given at the end of the article.

- spans: In linear algebra, the linear span (also called the linear hull or just span) of a set S of vectors in a vector space is the smallest linear subspace that contains the set

    - so we have a set of vectors => ${(-1,0,0),(0,1,0),(0,0,1)}$ is in vector space $R^3$
    
- Basis: In mathematics, a set B of elements (vectors) in a vector space V is called a basis, if every element of V may be written in a unique way as a (finite) linear combination of elements of B. The coefficients of this linear combination are referred to as components or coordinates on B of the vector. The elements of a basis are called basis vectors.

    - subset B of V is a basis if:
    
        - the linear independence property:
            - for every finite subset {b1, ..., bn} of B and every a1, ..., an in F, if a1b1 + ⋅⋅⋅ + anbn = 0, then a1 = ⋅⋅⋅ = an = 0;
        - the spanning property:
            - for every (vector) v in V, it is possible to choose v1, ..., vn in F and b1, ..., bn in B such that v = v1b1 + ⋅⋅⋅ + vnbn.

- linead dependence and independence

$\overrightarrow{a}$